### ISSUE TITLE
dicts are ordered

### ISSUE THREAD

**Issue by gelineau** [dabeaz-course/python-mastery#3]
In PythonMastery.pdf page 2-6, the sentence `An unordered set of values indexed by "keys"` should be changed, because dictionaries are ordered since Python 3.6

**Comment by dabeaz** [comment]
The essential programming concept (and common use) of a dict is an unordered mapping of values.   Although dicts are incidentally ordered by the insertion order of their keys (due to an underlying implementation detail), writing code that depends on the order of dictionary keys is not something that I would recommend in the general case nor is it a proper mental model for how dictionaries get used in most instances.

**Comment by gelineau** [comment]
dicts being ordered by the insertion order is not due to an underlying implementation detail.

> the insertion-order preservation nature of [dict](https://docs.python.org/3/library/stdtypes.html#typesmapping) objects [has been declared](https://mail.python.org/pipermail/python-dev/2017-December/151283.html) to be an official part of the Python language spec.

From: https://docs.python.org/3/whatsnew/3.7.html

**Comment by dabeaz** [comment]
Yes, but ordering is still not the essential feature of why one chooses to use a dictionary.  Nor is it safe to assume that a data presented in a dictionary is in any particular order unless you have full control over how that dictionary was actually created.   Also, no guarantees about order can be made once dictionaries start being mutated.   Order is also not considered when comparing dictionaries.

**Comment by dabeaz** [comment]
I've closing this issue because of my affinity for Chekov's gun.  https://en.wikipedia.org/wiki/Chekhov%27s_gun

The fact that dicts preserve order is interesting, but it's not a feature that is relied upon later in the course.   So, all things equal, I don't want to overwhelm people with "extra details."
